export const HOME_COUNTER_INCREMENT = 'HOME_COUNTER_INCREMENT';
export const HOME_COUNTER_DECREMENT = 'HOME_COUNTER_DECREMENT';
// Todos page
export const TODOS_ADD = 'TODOS: ADD';
export const TODOS_REMOVE = 'TODOS: REMOVE';
export const TODOS_TOGGLE_COMPLETE = 'TODOS_TOGGLE: COMPLETE';
